'use client';

import React from 'react';

const PrivacyPolicy: React.FC = () => {
  return (
    <div className="bg-white text-black dark:bg-gray-900 dark:text-gray-100 p-8 space-y-12">
      {/* Header Section */}
      <header className="text-center space-y-4 mb-16">
        <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 dark:text-slate-400 mb-4">Privacy Policy</h1>
        <p className="text-lg text-gray-600 dark:text-gray-300 max-w-2xl mx-auto">
          Your privacy is important to us. Learn how we handle your data and ensure your information is secure.
        </p>
      </header>

      {/* Information Collection Section */}
      <section className="bg-gray-100 dark:bg-gray-800 bg-opacity-90 shadow-lg rounded-lg p-6 sm:p-10 space-y-4">
        <h2 className="text-2xl sm:text-3xl font-semibold text-yellow-500 dark:text-yellow-400">Information Collection</h2>
        <p className="text-gray-700 dark:text-gray-300">
          We collect personal information that you provide to us directly, such as your name, email address, and payment details, as well as data automatically generated by your use of our platform.
        </p>
      </section>

      {/* How We Use Your Information Section */}
      <section className="bg-gray-100 dark:bg-gray-800 bg-opacity-90 shadow-lg rounded-lg p-6 sm:p-10 space-y-4">
        <h2 className="text-2xl sm:text-3xl font-semibold text-yellow-500 dark:text-yellow-400">How We Use Your Information</h2>
        <p className="text-gray-700 dark:text-gray-300">
          We use your information to deliver services, personalize your experience, improve our offerings, and communicate with you.
        </p>
      </section>

      {/* Data Security Section */}
      <section className="bg-gray-100 dark:bg-gray-800 bg-opacity-90 shadow-lg rounded-lg p-6 sm:p-10 space-y-4">
        <h2 className="text-2xl sm:text-3xl font-semibold text-yellow-500 dark:text-yellow-400">Data Security</h2>
        <p className="text-gray-700 dark:text-gray-300">
          We prioritize your data security and employ advanced measures to safeguard your information from unauthorized access.
        </p>
      </section>
    </div>
  );
};

export default PrivacyPolicy;
